//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 1/21/2023 10:15:32 AM
namespace Socrata
{
    /// <summary>
    /// There are no comments for Service in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Service")]
    public partial class Service : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Service object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public Service(global::System.Uri serviceRoot) :
                this(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
        }

        /// <summary>
        /// Initialize a new Service object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public Service(global::System.Uri serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion protocolVersion) :
                base(serviceRoot, protocolVersion)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "socrata", "Socrata");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            global::Microsoft.OData.Client.OriginalNameAttribute originalNameAttribute = (global::Microsoft.OData.Client.OriginalNameAttribute)global::System.Linq.Enumerable.SingleOrDefault(global::Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, typeof(global::Microsoft.OData.Client.OriginalNameAttribute), true));
            if (clientType.Namespace.Equals("Socrata", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("socrata.", originalNameAttribute.OriginalName);
                }
                return string.Concat("socrata.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for FoodTruck in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("rqzj-sfat")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<FoodTruck> FoodTruck
        {
            get
            {
                if ((this._FoodTruck == null))
                {
                    this._FoodTruck = base.CreateQuery<FoodTruck>("rqzj-sfat");
                }
                return this._FoodTruck;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<FoodTruck> _FoodTruck;
        /// <summary>
        /// There are no comments for FoodTruck in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToFoodTruck(FoodTruck rqzj)
        {
            base.AddObject("rqzj-sfat", rqzj);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private const string filePath = @"MobileFoodPermitsCsdl.xml";

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader();
                try
                {
                    global::System.Collections.Generic.IEnumerable<global::Microsoft.OData.Edm.Validation.EdmError> errors;
                    global::Microsoft.OData.Edm.IEdmModel edmModel;

                    if (!global::Microsoft.OData.Edm.Csdl.CsdlReader.TryParse(reader, true, out edmModel, out errors))
                    {
	                    global::System.Text.StringBuilder errorMessages = new global::System.Text.StringBuilder();
	                    foreach (var error in errors)
	                    {
		                    errorMessages.Append(error.ErrorMessage);
		                    errorMessages.Append("; ");
	                    }
	                    throw new global::System.InvalidOperationException(errorMessages.ToString());
                    }

                    return edmModel;
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader()
            {
                try
                {
                    var assembly = global::System.Reflection.Assembly.GetExecutingAssembly();
                    var resourcePath = global::System.Linq.Enumerable.Single(assembly.GetManifestResourceNames(), str => str.EndsWith(filePath));
                    global::System.IO.Stream stream = assembly.GetManifestResourceStream(resourcePath);
                    return global::System.Xml.XmlReader.Create(new global::System.IO.StreamReader(stream));
                }
                catch(global::System.Xml.XmlException e)
                {
                    throw new global::System.Xml.XmlException("Failed to create an XmlReader from the stream. Check if the resource exists.", e);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for FoodTruckSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("rqzj-sfatSingle")]
    public partial class FoodTruckSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<FoodTruck>
    {
        /// <summary>
        /// Initialize a new FoodTruckSingle object.
        /// </summary>
        public FoodTruckSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new FoodTruckSingle object.
        /// </summary>
        public FoodTruckSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new FoodTruckSingle object.
        /// </summary>
        public FoodTruckSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<FoodTruck> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for FoodTruck in the schema.
    /// </summary>
    /// <KeyProperties>
    /// __id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("__id")]
    [global::Microsoft.OData.Client.EntitySet("rqzj-sfat")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("rqzj-sfat")]
    public partial class FoodTruck : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new FoodTruck object.
        /// </summary>
        /// <param name="__id">Initial value of __id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static FoodTruck CreateFoodTruck(string __id)
        {
            FoodTruck rqzj = new FoodTruck();
            rqzj.__id = __id;
            return rqzj;
        }
        /// <summary>
        /// There are no comments for Property __id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("__id")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "__id is required.")]
        public virtual string __id
        {
            get
            {
                return this.___id;
            }
            set
            {
                this.On__idChanging(value);
                this.___id = value;
                this.On__idChanged();
                this.OnPropertyChanged("__id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string ___id;
        partial void On__idChanging(string value);
        partial void On__idChanged();
        /// <summary>
        /// There are no comments for Property Latitude in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("latitude")]
        public virtual global::System.Nullable<decimal> Latitude
        {
            get
            {
                return this._Latitude;
            }
            set
            {
                this.OnLatitudeChanging(value);
                this._Latitude = value;
                this.OnLatitudeChanged();
                this.OnPropertyChanged("latitude");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<decimal> _Latitude;
        partial void OnLatitudeChanging(global::System.Nullable<decimal> value);
        partial void OnLatitudeChanged();
        /// <summary>
        /// There are no comments for Property Y in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("y")]
        public virtual global::System.Nullable<decimal> Y
        {
            get
            {
                return this._Y;
            }
            set
            {
                this.OnYChanging(value);
                this._Y = value;
                this.OnYChanged();
                this.OnPropertyChanged("y");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<decimal> _Y;
        partial void OnYChanging(global::System.Nullable<decimal> value);
        partial void OnYChanged();
        /// <summary>
        /// There are no comments for Property Cnn in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("cnn")]
        public virtual global::System.Nullable<decimal> Cnn
        {
            get
            {
                return this._Cnn;
            }
            set
            {
                this.OnCnnChanging(value);
                this._Cnn = value;
                this.OnCnnChanged();
                this.OnPropertyChanged("cnn");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<decimal> _Cnn;
        partial void OnCnnChanging(global::System.Nullable<decimal> value);
        partial void OnCnnChanged();
        /// <summary>
        /// There are no comments for Property Permit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("permit")]
        public virtual string Permit
        {
            get
            {
                return this._Permit;
            }
            set
            {
                this.OnPermitChanging(value);
                this._Permit = value;
                this.OnPermitChanged();
                this.OnPropertyChanged("permit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Permit;
        partial void OnPermitChanging(string value);
        partial void OnPermitChanged();
        /// <summary>
        /// There are no comments for Property Fooditems in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("fooditems")]
        public virtual string Fooditems
        {
            get
            {
                return this._Fooditems;
            }
            set
            {
                this.OnFooditemsChanging(value);
                this._Fooditems = value;
                this.OnFooditemsChanged();
                this.OnPropertyChanged("fooditems");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Fooditems;
        partial void OnFooditemsChanging(string value);
        partial void OnFooditemsChanged();
        /// <summary>
        /// There are no comments for Property Objectid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("objectid")]
        public virtual global::System.Nullable<decimal> Objectid
        {
            get
            {
                return this._Objectid;
            }
            set
            {
                this.OnObjectidChanging(value);
                this._Objectid = value;
                this.OnObjectidChanged();
                this.OnPropertyChanged("objectid");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<decimal> _Objectid;
        partial void OnObjectidChanging(global::System.Nullable<decimal> value);
        partial void OnObjectidChanged();
        /// <summary>
        /// There are no comments for Property Expirationdate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("expirationdate")]
        public virtual string Expirationdate
        {
            get
            {
                return this._Expirationdate;
            }
            set
            {
                this.OnExpirationdateChanging(value);
                this._Expirationdate = value;
                this.OnExpirationdateChanged();
                this.OnPropertyChanged("expirationdate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Expirationdate;
        partial void OnExpirationdateChanging(string value);
        partial void OnExpirationdateChanged();
        /// <summary>
        /// There are no comments for Property Received in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("received")]
        public virtual string Received
        {
            get
            {
                return this._Received;
            }
            set
            {
                this.OnReceivedChanging(value);
                this._Received = value;
                this.OnReceivedChanged();
                this.OnPropertyChanged("received");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Received;
        partial void OnReceivedChanging(string value);
        partial void OnReceivedChanged();
        /// <summary>
        /// There are no comments for Property Location_zip in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("location_zip")]
        public virtual string Location_zip
        {
            get
            {
                return this._Location_zip;
            }
            set
            {
                this.OnLocation_zipChanging(value);
                this._Location_zip = value;
                this.OnLocation_zipChanged();
                this.OnPropertyChanged("location_zip");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Location_zip;
        partial void OnLocation_zipChanging(string value);
        partial void OnLocation_zipChanged();
        /// <summary>
        /// There are no comments for Property Location_state in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("location_state")]
        public virtual string Location_state
        {
            get
            {
                return this._Location_state;
            }
            set
            {
                this.OnLocation_stateChanging(value);
                this._Location_state = value;
                this.OnLocation_stateChanged();
                this.OnPropertyChanged("location_state");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Location_state;
        partial void OnLocation_stateChanging(string value);
        partial void OnLocation_stateChanged();
        /// <summary>
        /// There are no comments for Property Location_address in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("location_address")]
        public virtual string Location_address
        {
            get
            {
                return this._Location_address;
            }
            set
            {
                this.OnLocation_addressChanging(value);
                this._Location_address = value;
                this.OnLocation_addressChanged();
                this.OnPropertyChanged("location_address");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Location_address;
        partial void OnLocation_addressChanging(string value);
        partial void OnLocation_addressChanged();
        /// <summary>
        /// There are no comments for Property Noisent in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("noisent")]
        public virtual string Noisent
        {
            get
            {
                return this._Noisent;
            }
            set
            {
                this.OnNoisentChanging(value);
                this._Noisent = value;
                this.OnNoisentChanged();
                this.OnPropertyChanged("noisent");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Noisent;
        partial void OnNoisentChanging(string value);
        partial void OnNoisentChanged();
        /// <summary>
        /// There are no comments for Property Priorpermit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("priorpermit")]
        public virtual global::System.Nullable<decimal> Priorpermit
        {
            get
            {
                return this._Priorpermit;
            }
            set
            {
                this.OnPriorpermitChanging(value);
                this._Priorpermit = value;
                this.OnPriorpermitChanged();
                this.OnPropertyChanged("priorpermit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<decimal> _Priorpermit;
        partial void OnPriorpermitChanging(global::System.Nullable<decimal> value);
        partial void OnPriorpermitChanged();
        /// <summary>
        /// There are no comments for Property Approved in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("approved")]
        public virtual string Approved
        {
            get
            {
                return this._Approved;
            }
            set
            {
                this.OnApprovedChanging(value);
                this._Approved = value;
                this.OnApprovedChanged();
                this.OnPropertyChanged("approved");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Approved;
        partial void OnApprovedChanging(string value);
        partial void OnApprovedChanged();
        /// <summary>
        /// There are no comments for Property X in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("x")]
        public virtual global::System.Nullable<decimal> X
        {
            get
            {
                return this._X;
            }
            set
            {
                this.OnXChanging(value);
                this._X = value;
                this.OnXChanged();
                this.OnPropertyChanged("x");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<decimal> _X;
        partial void OnXChanging(global::System.Nullable<decimal> value);
        partial void OnXChanged();
        /// <summary>
        /// There are no comments for Property Block in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("block")]
        public virtual string Block
        {
            get
            {
                return this._Block;
            }
            set
            {
                this.OnBlockChanging(value);
                this._Block = value;
                this.OnBlockChanged();
                this.OnPropertyChanged("block");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Block;
        partial void OnBlockChanging(string value);
        partial void OnBlockChanged();
        /// <summary>
        /// There are no comments for Property Facilitytype in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("facilitytype")]
        public virtual string Facilitytype
        {
            get
            {
                return this._Facilitytype;
            }
            set
            {
                this.OnFacilitytypeChanging(value);
                this._Facilitytype = value;
                this.OnFacilitytypeChanged();
                this.OnPropertyChanged("facilitytype");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Facilitytype;
        partial void OnFacilitytypeChanging(string value);
        partial void OnFacilitytypeChanged();
        /// <summary>
        /// There are no comments for Property Locationdescription in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("locationdescription")]
        public virtual string Locationdescription
        {
            get
            {
                return this._Locationdescription;
            }
            set
            {
                this.OnLocationdescriptionChanging(value);
                this._Locationdescription = value;
                this.OnLocationdescriptionChanged();
                this.OnPropertyChanged("locationdescription");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Locationdescription;
        partial void OnLocationdescriptionChanging(string value);
        partial void OnLocationdescriptionChanged();
        /// <summary>
        /// There are no comments for Property Lot in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("lot")]
        public virtual string Lot
        {
            get
            {
                return this._Lot;
            }
            set
            {
                this.OnLotChanging(value);
                this._Lot = value;
                this.OnLotChanged();
                this.OnPropertyChanged("lot");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Lot;
        partial void OnLotChanging(string value);
        partial void OnLotChanged();
        /// <summary>
        /// There are no comments for Property Schedule in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("schedule")]
        public virtual string Schedule
        {
            get
            {
                return this._Schedule;
            }
            set
            {
                this.OnScheduleChanging(value);
                this._Schedule = value;
                this.OnScheduleChanged();
                this.OnPropertyChanged("schedule");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Schedule;
        partial void OnScheduleChanging(string value);
        partial void OnScheduleChanged();
        /// <summary>
        /// There are no comments for Property Dayshours in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("dayshours")]
        public virtual string Dayshours
        {
            get
            {
                return this._Dayshours;
            }
            set
            {
                this.OnDayshoursChanging(value);
                this._Dayshours = value;
                this.OnDayshoursChanged();
                this.OnPropertyChanged("dayshours");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Dayshours;
        partial void OnDayshoursChanging(string value);
        partial void OnDayshoursChanged();
        /// <summary>
        /// There are no comments for Property Location in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("location")]
        public virtual global::Microsoft.Spatial.GeographyPoint Location
        {
            get
            {
                return this._Location;
            }
            set
            {
                this.OnLocationChanging(value);
                this._Location = value;
                this.OnLocationChanged();
                this.OnPropertyChanged("location");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.Spatial.GeographyPoint _Location;
        partial void OnLocationChanging(global::Microsoft.Spatial.GeographyPoint value);
        partial void OnLocationChanged();
        /// <summary>
        /// There are no comments for Property Blocklot in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("blocklot")]
        public virtual string Blocklot
        {
            get
            {
                return this._Blocklot;
            }
            set
            {
                this.OnBlocklotChanging(value);
                this._Blocklot = value;
                this.OnBlocklotChanged();
                this.OnPropertyChanged("blocklot");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Blocklot;
        partial void OnBlocklotChanging(string value);
        partial void OnBlocklotChanged();
        /// <summary>
        /// There are no comments for Property Location_city in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("location_city")]
        public virtual string Location_city
        {
            get
            {
                return this._Location_city;
            }
            set
            {
                this.OnLocation_cityChanging(value);
                this._Location_city = value;
                this.OnLocation_cityChanged();
                this.OnPropertyChanged("location_city");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Location_city;
        partial void OnLocation_cityChanging(string value);
        partial void OnLocation_cityChanged();
        /// <summary>
        /// There are no comments for Property Longitude in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("longitude")]
        public virtual global::System.Nullable<decimal> Longitude
        {
            get
            {
                return this._Longitude;
            }
            set
            {
                this.OnLongitudeChanging(value);
                this._Longitude = value;
                this.OnLongitudeChanged();
                this.OnPropertyChanged("longitude");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<decimal> _Longitude;
        partial void OnLongitudeChanging(global::System.Nullable<decimal> value);
        partial void OnLongitudeChanged();
        /// <summary>
        /// There are no comments for Property Applicant in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("applicant")]
        public virtual string Applicant
        {
            get
            {
                return this._Applicant;
            }
            set
            {
                this.OnApplicantChanging(value);
                this._Applicant = value;
                this.OnApplicantChanged();
                this.OnPropertyChanged("applicant");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Applicant;
        partial void OnApplicantChanging(string value);
        partial void OnApplicantChanged();
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("status")]
        public virtual string Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this._Status = value;
                this.OnStatusChanged();
                this.OnPropertyChanged("status");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Status;
        partial void OnStatusChanging(string value);
        partial void OnStatusChanged();
        /// <summary>
        /// There are no comments for Property Address in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("address")]
        public virtual string Address
        {
            get
            {
                return this._Address;
            }
            set
            {
                this.OnAddressChanging(value);
                this._Address = value;
                this.OnAddressChanged();
                this.OnPropertyChanged("address");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Address;
        partial void OnAddressChanging(string value);
        partial void OnAddressChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::Socrata.FoodTruck as global::Socrata.FoodTruckSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::Socrata.FoodTruckSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Socrata.FoodTruck> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::Socrata.FoodTruckSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Socrata.FoodTruck as global::Socrata.FoodTruckSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="__id">The value of __id</param>
        public static global::Socrata.FoodTruckSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Socrata.FoodTruck> _source,
            string __id)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "__id", __id }
            };
            return new global::Socrata.FoodTruckSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
    }
}
